[workspace]

members = [    
    "navigation",
    "physics",
    "stacktrader-types",
    "radar",
    "mining",
    "genesis",
    "merchant"
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
